adamchainz/gargoyle

- .travis.yml
- Makefile
- README.rst
- docs/conf.py
- gargoyle/__init__.py
- gargoyle/compat.py
- gargoyle/manager.py
- requirements.txt
- tests/settings.py
- tests/urls.py
* Made Travis work
* Updated README: Fixed badges, added fork note, requirements, and install sections
* Also added link to our documentation on Read The Docs, though this still requires some more work to get building
> Fix Travis and update README

- gargoyle/nexus_modules.py
Found this whilst upgrading to Python 3.
> Remove old Django 1.4 compatibility code

- requirements.txt
- tests/requirements.txt
- tox.ini
Move `requirements.txt` into `tests`, and freeze all requirement versions so builds are repeatable.
> Tidy testing

- gargoyle/models.py
- tests/testapp/test_builtins.py
> Test IPAddressConditionSet

- README.rst
- docs/index.rst
- docs/install.rst
- docs/ref/signals.rst
- docs/usage.rst
- gargoyle/manager.py
- gargoyle/models.py
- gargoyle/testutils.py
* Fix install instruction to `gargoyle-yplan`
* Tidy highlighting
* Tidy directory structure
* Fix example code to be Python 3 compatible
> Tidy up documentation

- HISTORY.rst
- gargoyle/media/js/gargoyle.js
- gargoyle/templates/gargoyle/index.html
Fixes #11. We now adhere to the Django Admin security policy on inline javascript.
> Remove all inline Javascript

- HISTORY.rst
- docs/usage.rst
- gargoyle/templatetags/gargoyle_tags.py
- tests/testapp/test_template_tags.py
Merge of disqus/gargoyle#92. Thanks @mrfuxi.
> Add ifnotswitch template tag

- setup.py
> setup.py - stop distributing tests

- gargoyle/nexus_modules.py
* Remove GARGOYLE_ROOT, unused since ebb48a93ece40de623c1063e2fd337bc7486b641
* Change `json` into `@json_view`, use it as a decorator like we can now we no longer support older Python versions
> Tidy up some code

- tests/testapp/test_api.py
- tests/testapp/test_template_tags.py
Shrink many things onto one line, remove old modeldict compat lines
> Tidy tests

- gargoyle/media/js/gargoyle.js
> Use jQuery.data() for data attributes

- HISTORY.rst
- gargoyle/compat.py
- gargoyle/testutils.py
- setup.py
- tests/testapp/test_testutils.py
> Made @switches usable as a TestCase class decorator

- setup.cfg
- tests/requirements.txt
> Tests - add coverage

- HISTORY.rst
- gargoyle/conditions.py
These were added in b16680706869d9ed802b47708a435b1e6691685a.
> Remove debug prints from conditions.py

- HISTORY.rst
> HISTORY - fix some syntax highlighting

- gargoyle/management/commands/add_switch.py
- gargoyle/management/commands/remove_switch.py
- tests/testapp/test_commands.py
> Convert management commands to argparse

- runtests.py
- setup.cfg
- setup.py
- tests/README.rst
- tests/requirements.txt
- tox.ini
Remove the cargo-culted runtests.py
> Use multilint

- HISTORY.rst
- setup.py
> Disallow django-jsonfield==1.0.0 in requirements

- gargoyle/__init__.py
- gargoyle/templatetags/__init__.py
- runtests.py
- setup.cfg
- tests/__init__.py
...and fix the lint errors it shows up.
> Add mising multilint config

- gargoyle/models.py
- gargoyle/nexus_modules.py
- tests/testapp/test_api.py
Addresses https://github.com/adamchainz/gargoyle/issues/207
> Prevent conflicting conditions from being added
