adamchainz/gargoyle

gargoyle/builtins.py, gargoyle/conditions.py, gargoyle/models.py, gargoyle/nexus_modules.py, gargoyle/templates/gargoyle/index.html, gargoyle/templatetags/gargoyle_helpers.py, gargoyle/templatetags/gargoyle_tags.py, gargoyle/testutils.py
Since we only support Django 1.7+ and Python 2.7+ now, we can tidy this all up.
=> Remove all compatibility code for Django < 1.7 / Python < 2.7

HISTORY.rst, README.rst, setup.py
Done so we can add Django 1.9 and Python 3 compatibility.
=> Use the YPlan fork of django-modeldict

HISTORY.rst, README.rst, tests/settings.py, tox.ini
It's no longer supported by Django, so we don't need to either.
=> Remove support for Django 1.7

setup.py, tox.ini
This is the version that supports Python 3, and now we support Python 3, we require it.
=> Require nexus-yplan >= 1.1

requirements.txt
Unfix `py`, it should be installed as a dependency of `pytest`.
=> Tidy requirements

HISTORY.rst, gargoyle/templates/gargoyle/index.html
These were broken in 73f82a3a0ed6ca09f363efd3a2f727e4114a3edb with the move from `{% raw %}` to `{% verbatim %}`. The key oversight was that `raw`'s implementation would convert `{{ x }}` into `{{x}}` since it was implemented post-parse and reconstructed the braces - and the `jQuery.tmpl` plugin would only work with no spaces.
Tested by replacing this file in our local app, it worked. Next time javascript-affecting changes will be tested more thoroughly.
=> Fix jQuery templates

HISTORY.rst, gargoyle/media/js/gargoyle.js, setup.py
Merges disqus/gargoyle#73. This fixes the cases with newer jQuery where selector contains dot characters.
=> Wrap id's of selectors in quotes

HISTORY.rst, gargoyle/templates/gargoyle/index.html
Fixes the issue reported in disqus/gargoyle#98, thanks @arnaudlimbourg.
Turns out that the rows were being assigned HTML ID's, which are not
allowed to feature spaces, however this is unneccesary since we only use
the `data-` attributes to reference the HTML.
=> Fix Nexus admin interface for Switches with spaces in their keys

HISTORY.rst, docs/install.rst, gargoyle/__init__.py, gargoyle/apps.py, gargoyle/nexus_modules.py
Fixes #10. Makes installation simpler and autodiscovery more predictable.
=> Move autodiscovery to AppConfig.ready

gargoyle/__init__.py
523c25807d6e4b2d356580e515258d67a0794d95 broke autodiscovery for applications
that do not import `gargoyle.builtins` anywhere themselves, as it removed the
line that imported them.
=> Fix autodiscovery

HISTORY.rst, gargoyle/nexus_modules.py, tests/settings/base.py, tests/settings/test.py, tests/urls.py
Fixes a couple issues that appear for tests and main code:
* urls `patterns` is deprecated
* `TEMPLATE_DEBUG` no longer exists
=> Fix Django compatibility

gargoyle/templates/gargoyle/nexus/dashboard.html
Fixes 'RemovedInDjango110Warning: The old {% cycle %} syntax with comma-separated arguments is deprecated.'.
=> Fix template tag 'cycle' warning on Django 1.9

tests/testapp/test_api.py, tests/testapp/test_builtins.py, tests/testapp/test_commands.py, tests/testapp/test_helpers.py, tests/testapp/test_manager.py, tests/testapp/test_template_tags.py, tests/testapp/test_testutils.py
Makes the tests a lot nicer, plus found a load of un-run asserts! Luckily only one of them was actually wrong.
=> Convert all unittest assert function calls to pytest-style plain assert statements

HISTORY.rst, gargoyle/testutils.py, tests/testapp/test_testutils.py
It wasn't wrapping properly because it implemented __call__ which overrode the implementation in ContextDecorator.
Properly checked this time that the new test case was collected by pytest.
=> Fix @switches

HISTORY.rst, gargoyle/migrations/0002_bytes_to_str.py, tests/testapp/test_models.py
Fixes #70. This migration is no-op.
Also added a test that ensures that no migrations are required, it fails before this change and passes after.
=> Add migration changing 'choices' for Switch.status from bytes to str

HISTORY.rst, gargoyle/builtins.py, gargoyle/manager.py, tests/testapp/test_api.py
=> Make gargoyle.register() usable as a decorator, and gargoyle.unregister() return whether it unregistered

tests/testapp/test_api.py, tests/urls.py
Redirect from `/` to `/nexus/` so one doesn't need to remember to do that after starting `./manage.py runserver`.
=> Make 'development mode' easier to use

HISTORY.rst, gargoyle/nexus_modules.py, tests/testapp/test_api.py
Fixes #55. The API the frontend uses is untested, maybe some tests would have caught it.
=> Fixed removing conditions in the UI where the value is the empty string

README.rst
The build status was unknown because it was pointing to the old "yplan" org.
=> Update travis badge

docs/conf.py
In particular this impacts the ConditionSet API documentation.
This will cause documentation builds on older Django versions to fail (<1.9 I think).
=> Fix import error in documentation build. 
